### ISSUE TITLE
Backend down когда запускаешь под boot2docker внутри virtualbox

### ISSUE THREAD

**Issue by svetlyak40wt** [shoonoise/cabot-docker#20]
Я клонировал себе репозиторий как есть, но пришлось немного урезать конфиг maestro, выкинув оттуда exim, так как он очевидно, в каком-то приватном репозитории яндекса:

И я немного модифицировал конфиг с тем, чтобы поднять всё внутри локально запущенного VirtualBox:

```
name: cabot

ships:
  vm1:
    ip: 192.168.59.103
    endpoint: boot2docker
    docker_port: 2376
    tls: true
    tls_verify: true
    tls_ca_cert: /Users/art/.boot2docker/certs/boot2docker-vm/ca.pem
    tls_key: /Users/art/.boot2docker/certs/boot2docker-vm/key.pem
    tls_cert: /Users/art/.boot2docker/certs/boot2docker-vm/cert.pem
    
services:
  cabot_web:
    image: wondermall/cabot
    requires: [database, celery_broker]
    instances:
      cabot:
        ship: vm1
        ports: {backend: 5000, web: 80}
        env:
          HIPCHAT_ALERT_ROOM: __FIX_ME__
          HIPCHAT_API_KEY: __FIX_ME__
  database:
    image: orchardup/postgresql
    instances:
      postgre:
        ship: vm1
        ports: {db: 5432}
        volumes:
          /var/lib/postgresql: /var/lib/cabotdb
        env:
          POSTGRESQL_USER: docker
          POSTGRESQL_PASS: docker
          POSTGRESQL_DB: docker
  celery_broker:
    image: redis
    instances:
      redis:
        ship: vm1
        ports: {broker: 6379}
  # mail:
  #   image: yandex/exim
  #   instances:
  #     exim:
  #       ship: vm1
  #       ports: {smtp: "25:225"}
```

Под maestro это всё стартануло, но `maestro status -F` почему-то выдает:

```
backend:  5000/tcp is down
```

При этом на хост машине 80 порт доступен, Cabot там работает и у меня даже получилось завести проверку и сервис. А когда я сервис погасил, то проверка сработала.

Почему `backend is down`, но при этом кажется, что сервис работает?
